#大小写敏感
#数据值前边必须有空格，作为分隔符
#使用缩进表示层级关系
#缩进时不允许使用Tab键，只允许使用空格
#缩进的空格数目不重要，只要相同层级的元素左侧对其即可
# #表示注释，从这个字符一直到行尾，都会被解析器忽略

server:
  port: 8082
  address: 127.0.0.1

name: zhangsan

#对象格式
person:
  name: lisi
  age: 20
#对象格式行内写法
person1: {name: lisi,age: 20}

#参数引用
person2:
  name: ${name}

#数组格式(使用-表示数组的每个元素)
address:
  - beijing
  - shanghai
#数组格式的行内写法
address1: [beijing,shanghai]

#纯量
msg1: 'hello \n world' #单引号不会识别转义字符，按原样输出
msg2: "hello \n world" #双引号会识别转义字符

#yml多文档方式：用---分隔不同配置
---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
---

---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: pro
---

---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: test
---

---
#激活指定配置文件
spring:
  profiles:
    active: test
#profile激活方式：1.配置文件：在配置文件中配置：spring.profiles.active=dev;
#               2.虚拟机参数:在VM options指定：-Dspring.profiles.active=dev;
#               3.命令行参数：java -jar xxx.jar --spring.profiles.active=dev;3.命令行参数:java-jar xxx.jar --spring.profiles.active=dev
---

---
#redis配置
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
---

---
#datasource配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
---

---
#Mybitas配置
mybatis:
  mapper-locations: classpath:mapper/*.xml #Mapper的映射文件路径
  # config-location: #指定Mybatis的核心配置文件
  type-aliases-package: com.qvtu.domain #指定实体类的包路径
---